### ISSUE TITLE
not working for local files

### ISSUE THREAD

**Issue by 517qf** [brynedwards/readability-wrapper#2]
Thanks for this fantastisc program which allows to bring pages into my plain text archive. But I would also like to clean old articles I have saved locally with names like `/home/username/docs/article.html`. Unfortunately I hardly know js.

I can run `readability non-local-url` but I get errors when I try to run `readability file:///home/myusername/test.html` or `readability /home/myusername/test.html`. I get these error-messages:

```
(node:5872) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): RequestError: Error: Invalid URI "file:///home/mateo/test.html"
(node:5872) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

My environment: 

- A freshly installed vm with the latest ubuntu (1804).
- Then I downloaded the compiled version of nodejs version 7.10.0 and unpacked it.
- I added the bin folder from the node folder and ~/node-packages/.bin to my PATH and ran `npm install readability-wrapper` 

When I run this on my main machine with node 8.11.1 I get a more verbose error.

```
(node:12311) UnhandledPromiseRejectionWarning: RequestError: Error: Invalid URI "file:///home/username/test.html"
    at new RequestError (/home/username/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/home/username/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/home/username/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/home/username/node_modules/request/request.js:186:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.init (/home/username/node_modules/request/request.js:274:17)
    at Request.RP$initInterceptor [as init] (/home/username/node_modules/request-promise-core/configure/request2.js:45:29)
    at new Request (/home/username/node_modules/request/request.js:128:8)
    at request (/home/username/node_modules/request/index.js:53:10)
(node:12311) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:12311) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

Similarly I can't run `curl non-local-url` | readability`. I get the message `Please provide a URL`

**Comment by brynedwards** [comment]
Hi, sorry, I never updated the npm package since the piping option was added. Try updating it and then run e.g. `readability < /home/username/docs/article.html`

**Comment by 517qf** [comment]
Everything runs perfectly now. Checking the installed version against the latest on github should have occured to me ....

Thanks for your quick help!

After confirming that it works with the package from npm I downloaded the source and tried with newer versions of readability-js. I tried with a few urls that needed converting and it works up to commit 5ee03bc from  2018-04-22. But I get an error if I try with the next commit d601849 from 2018-04-26 .

The error report I get (using node 8.11.1 with readability-js at commit d601849) is: 

(I suspect this is an upstream problem?)

```
(node:30526) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'firstElementChild' of undefined
    at Readability.parse (/home/username/node_modules/readability-wrapper/node_modules/readability/Readability.js:1723:42)
    at then.dom (/home/username/node_modules/readability-wrapper/index.js:34:61)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:30526) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30526) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by brynedwards** [comment]
Yeah I just had a look at the commit, looks like they made a minor change to how readability-js is used, it's a trivial fix. Thanks for finding the problematic commit.
